### ISSUE TITLE
求助:查询mysql遇到问题.

### ISSUE THREAD

**Issue by warm-dawn** [sniper00/moon#134]
我结合hello world例程和mysql例程写了一个测试使用mysql例程.
功能简单, 若接收到客户端发来的指定字符串'dbtest' 就从mydb中查询所有表名, 其结果直接发送给客户端作为回复.
代码如下
![image](https://user-images.githubusercontent.com/59309812/109501475-9830fc00-7ad2-11eb-9740-6fca6de26a7b.png)
![image](https://user-images.githubusercontent.com/59309812/109501498-a1ba6400-7ad2-11eb-8749-1bac1725286c.png)
报错如下:
![image](https://user-images.githubusercontent.com/59309812/109501659-e1814b80-7ad2-11eb-806d-b0a28036f969.png)

1. 在on message里直接写mysql连接查询 就会报错, 所以只能在协程里写.
2. 在协程中写, 本框架不能使用全局变量, 所以函数必须传参.
这种情况下该怎么传参到匿名函数中?
卡了很久了, 网上搜不到, lua的pdf我也下了看, 但我还是不知道这种该怎么写, 求助一下.

**Comment by sniper00** [comment]
local funtion db_test

**Comment by sniper00** [comment]
另外 db查询结果是一个lua table ，你可以用json encode转成字符串后再通过网络发送
