### ISSUE TITLE
疑问:list.lua queue.size(q)的大小

### ISSUE THREAD

**Issue by axiullo** [sniper00/moon#152]
list.lua queue.size(q) 获得队列的大小为什么不是 q.t -q.h +1 ?  queue.push的时候是t+1,  pop的时候是h + 1.

**Comment by sniper00** [comment]
感谢指出，可以这样判断，see [08638f3](https://github.com/sniper00/moon/commit/08638f3a727f2ebde0f8d0e205237cdd1e99bb11)
