### ISSUE TITLE
mooncore这个lua文件在哪里呀？

### ISSUE THREAD

**Issue by aihuanhuan** [sniper00/moon#157]
作者您好！
运行main_hub.lua ，提示module 'mooncore' not found，请问如何处理？
![1678183468500](https://user-images.githubusercontent.com/35648677/223389986-f46c85f9-1cd2-42ec-9bc1-028c5c596554.png)

**Comment by sniper00** [comment]
需要编译moon 用moon启动，如果你只是想尝试下可以下载编译好的版本

**Comment by sniper00** [comment]
> 作者您好！
> 
> 运行main_hub.lua ，提示module 'mooncore' not found，请问如何处理？
> 
> ![1678183468500](https://user-images.githubusercontent.com/35648677/223389986-f46c85f9-1cd2-42ec-9bc1-028c5c596554.png)
> 
> 

https://github.com/sniper00/moon/releases/tag/v0.7
