### ISSUE TITLE
vs2022编译最新版本代码失败，mimalloc（看着是2017版编译的）解析失败了。

### ISSUE THREAD

**Issue by crazyDon** [sniper00/moon#160]
BUILDVCTOOLS: C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git

Microsoft Visual Studio 2022 版本 17.6.4.
版权所有(C) Microsoft Corp.。保留所有权利。
已启动重新生成...
1>------ 已启动全部重新生成: 项目: sharetable, 配置: Release x64 ------
2>------ 已启动全部重新生成: 项目: pb, 配置: Release x64 ------
3>------ 已启动全部重新生成: 项目: mongo, 配置: Release x64 ------
4>------ 已启动全部重新生成: 项目: mimalloc, 配置: Release x64 ------
5>------ 已启动全部重新生成: 项目: lualib, 配置: Release x64 ------
6>------ 已启动全部重新生成: 项目: lua, 配置: Release x64 ------
7>------ 已启动全部重新生成: 项目: crypt, 配置: Release x64 ------
1>lua-sharetable.c
2>pb.c
3>lua-bson.c
1>sharetable.vcxproj -> G:\unityProj\2D\KnightsLike\Moon\moon-master\build\bin\Release\sharetable.lib
4>static.c
4>c1 : fatal  error C1083: 无法打开源文件: “..\..\..\third\mimalloc\src\static.c”: No such file or directory
4>已完成生成项目“mimalloc.vcxproj”的操作 - 失败。

**Comment by sniper00** [comment]
git submodule init. git submodule update

**Comment by crazyDon** [comment]
git clone 下来的可以编译了，dowload zip的不行
