### ISSUE TITLE
请问 lua_service::dispatch 中调用的是什么函数，没看出来哪里推入栈的

### ISSUE THREAD

**Issue by xukeawsl** [sniper00/moon#172]

**Comment by sniper00** [comment]
> _No description provided._

在这里注册的 https://github.com/sniper00/moon/blob/master/moon-src/services/lua_service.cpp#L156

这样写的原因是参考 https://blog.codingnow.com/2022/04/lua_binding_callback.html#more

**Comment by xukeawsl** [comment]
谢谢你的回复，我想我应该先多了解一下 Lua，现在还不太能理解
