### ISSUE TITLE
升级代码后，之前版本正常。

### ISSUE THREAD

**Issue by lonag** [sniper00/moon#173]
2024-07-15 21:00:00.114 | 38076     | DEBUG | server::response dispatch db_game error:
moon/lualib/moon.lua:395: [db_game] dispatch PTYPE [4] is nil
stack traceback:
	[C]: in function 'error'
	moon/lualib/moon.lua:395: in function <moon/lualib/moon.lua:372> (server.cpp:335)
2024-07-15 21:00:00.115 | 38076     | DEBUG | server::response dispatch db_game error:
moon/lualib/moon.lua:395: [db_game] dispatch PTYPE [4] is nil
stack traceback:
	[C]: in function 'error'
	moon/lualib/moon.lua:395: in function <moon/lualib/moon.lua:372> (server.cpp:335)

**Comment by sniper00** [comment]
谢谢，这个有复现步骤吗？

**Comment by lonag** [comment]
我逻辑是毕现

**Comment by lonag** [comment]
我这个代码

**Comment by lonag** [comment]
function Auth.CallUser(uid,cmd,...)
    if context.server_exit then
        error(string.format("call user %d cmd %s when server exit", uid, cmd))
    end
    print("try call user" ,uid)
    local u = context.uid_map[uid]
    local err = nil
    local user = nil
    if not u then
        u, err = Auth.PullUser(uid)
        if not u then
            print("not u",uid)
            return false, err
        end

        if u.logouttime > 0 then
            u.logouttime = moon.time()
        end
        user = moon.call("lua", u.addr_user, cmd,...)
        QuitOneUser(u)
    else--在线
        user = moon.call("lua", u.addr_user, cmd,...) 
    end
    return user
end

**Comment by lonag** [comment]
`function Auth.CallUser(uid,cmd,...)
    if context.server_exit then
        error(string.format("call user %d cmd %s when server exit", uid, cmd))
    end
    print("try call user" ,uid)
    local u = context.uid_map[uid]
    local err = nil
    local user = nil
    if not u then
        u, err = Auth.PullUser(uid)
        if not u then
            print("not u",uid)
            return false, err
        end

        if u.logouttime > 0 then
            u.logouttime = moon.time()
        end
        user = moon.call("lua", u.addr_user, cmd,...)
        QuitOneUser(u)
    else--在线
        user = moon.call("lua", u.addr_user, cmd,...) 
    end
    return user
end`

**Comment by lonag** [comment]
把uid放到list里面，让后用onhour 到时间调用，就能毕现。这些都是moondemo相关的，你应该知道
我是竞技场定时发奖励，就会这样

**Comment by lonag** [comment]
报错的是那个name为error的protocal

**Comment by sniper00** [comment]
我尝试了下没有复现，麻烦你把 moon.lua 482行替换下,打印下具体数据
```lua
reg_protocol {
    name = "error",
    PTYPE = moon.PTYPE_ERROR,
    pack = function(...)
        return ...
    end,
    unpack = function(sz, len)
        local data = moon.tostring(sz, len) or "unknown error"
        return false, data
    end,
    dispatch = function(...)
        moon.error(...)
        error("PTYPE_TEXT dispatch not implemented")
    end
}
```

**Comment by lonag** [comment]
我看看

**Comment by lonag** [comment]
`2024-07-18 09:00:00.361 | :02000001 | ERROR | userdata: 00000240950D5E70    (moon/lualib/moon.lua:494)
2024-07-18 09:00:00.361 | 7980      | DEBUG | server::response dispatch db_game error:
moon/lualib/moon.lua:495: PTYPE_TEXT dispatch not implemented
stack traceback:
	[C]: in function 'error'
	moon/lualib/moon.lua:495: in local 'dispatch'
	moon/lualib/moon.lua:406: in function <moon/lualib/moon.lua:372> (server.cpp:335)`

**Comment by lonag** [comment]
没啥用，看不出啥

**Comment by sniper00** [comment]
注意修改部分原代码有个israw 属性，要去掉这个属性

**Comment by lonag** [comment]
嗯，确实，没改

**Comment by lonag** [comment]
`2024-07-18 10:00:00.150 | :02000001 | ERROR | 0    -4    false    [02000001] attempt send to dead service [0A000001]: 066c7761726e696e675f636f756e74026c7365727665725f7374617475730a026c61666665637465645f726f77730a014c696e736572745f69640200.    (moon/lualib/moon.lua:494)
2024-07-18 10:00:00.150 | 32516     | DEBUG | server::response dispatch db_game error:
moon/lualib/moon.lua:111: moon/lualib/moon.lua:495: PTYPE_TEXT dispatch not implemented
stack traceback:
	[C]: in function 'error'
	moon/lualib/moon.lua:495: in local 'fn'
	moon/lualib/moon.lua:228: in upvalue 'invoke'
	moon/lualib/moon.lua:235: in function <moon/lualib/moon.lua:233>
stack traceback:
	[C]: in function 'error'
	moon/lualib/moon.lua:111: in upvalue 'coresume'
	moon/lualib/moon.lua:404: in function <moon/lualib/moon.lua:372> (server.cpp:335)`

**Comment by sniper00** [comment]
> `2024-07-18 10:00:00.150 | :02000001 | ERROR | 0 -4 false [02000001] attempt send to dead service [0A000001]: 066c7761726e696e675f636f756e74026c7365727665725f7374617475730a026c61666665637465645f726f77730a014c696e736572745f69640200. (moon/lualib/moon.lua:494) 2024-07-18 10:00:00.150 | 32516 | DEBUG | server::response dispatch db_game error: moon/lualib/moon.lua:111: moon/lualib/moon.lua:495: PTYPE_TEXT dispatch not implemented stack traceback: [C]: in function 'error' moon/lualib/moon.lua:495: in local 'fn' moon/lualib/moon.lua:228: in upvalue 'invoke' moon/lualib/moon.lua:235: in function <moon/lualib/moon.lua:233> stack traceback: [C]: in function 'error' moon/lualib/moon.lua:111: in upvalue 'coresume' moon/lualib/moon.lua:404: in function <moon/lualib/moon.lua:372> (server.cpp:335)`

你先这样改下，应该可以解决问题了, https://github.com/sniper00/moon/blob/master/moon-src/core/worker.cpp#L274 这个位置改成:
```cpp
                  if(msg.sessionid()>=0){
                        log::instance().logstring(true, moon::LogLevel::Debug, str, id());
                    }else{
                        msg.set_sessionid(-msg.sessionid());
                        server_->response(sender, str, msg.sessionid(), PTYPE_ERROR);
                    }
```

**Comment by sniper00** [comment]
原因就是 A moon.call(B),   然后A 退出， B返回数据给A, 这时底层检测到A不存在了, 只要打印  [02000001] attempt send to dead service [0A000001]即可 , 代码没有判断session>0,造成把这个错误日志返回给B了

**Comment by lonag** [comment]
ok

**Comment by sniper00** [comment]
@lonag master上修复了, 有空可以试试
