### ISSUE TITLE
mysql接口会导致服务器cpu利用率飙升，到99%

### ISSUE THREAD

**Issue by lonag** [sniper00/moon#175]
moon.db.mysql使用这个接口，db_game,无法save_then_quit后退出进程，关闭服务器失败
前提是cpu占用99%

**Comment by lonag** [comment]
可能不是这个问题，我先关闭吧

**Comment by lonag** [comment]
先开着吧，还是不能排除

**Comment by sniper00** [comment]
> 先开着吧，还是不能排除

进程关闭需要等待所有服务退出，你99%cpu占用 估计是某个线程死循环了

**Comment by lonag** [comment]
打扰，大概知道了，自己代码问题
