### ISSUE TITLE
后面会不会提供类似skynet的gate模块？

### ISSUE THREAD

**Issue by jstinapoll** [sniper00/moon#178]

**Comment by sniper00** [comment]
> _No description provided._

moon底层已经提供了，稍微包装下就是gate服务
https://github.com/sniper00/MoonDemo/blob/master/server/game/service_gate.lua

**Comment by jstinapoll** [comment]
好滴 感谢大佬

**Comment by jstinapoll** [comment]
战斗部分想用ecs这种架构，有没有比较好用的库推荐一下（能与这个游戏服务器框架比较好结合的）？

**Comment by sniper00** [comment]
> 战斗部分想用ecs这种架构，有没有比较好用的库推荐一下（能与这个游戏服务器框架比较好结合的）？

战斗部分一般比较独立，我暂时没比较好的方案，你可以自己研究下

**Comment by jstinapoll** [comment]
大佬 服务器用moon这个框架 客户端用Unity3d c#语言开发  战斗逻辑是写两套不同语言的？ 还是https://github.com/Manistein/SparkServer 类似于这种 战斗框架单独出来 双端共用呢  哪种方案好点

**Comment by sniper00** [comment]
> 大佬 服务器用moon这个框架 客户端用Unity3d c#语言开发 战斗逻辑是写两套不同语言的？ 还是https://github.com/Manistein/SparkServer 类似于这种 战斗框架单独出来 双端共用呢 哪种方案好点

复杂的需要物理引擎的战斗建议用unity写 如射击类游戏

**Comment by jstinapoll** [comment]
好滴 感谢大佬 我研究一下
