### ISSUE TITLE
这个大体的思路是不是和skynet比较类似

### ISSUE THREAD

**Issue by yingnierxiao** [sniper00/moon#181]
ag多的话内存会不会涨的比较厉害

**Comment by sniper00** [comment]
## moon和skynet的区别主要是调度模型的区别

## skynet是 `One queue, many processors`
> 在这个模型中，有一个全局的 run_queue，当 tasks 变得可运行时，就会被推入队尾。还有多个处理器，每个都运行在独立的线程中。当队列中没有任务的时候，就阻塞住线程，当有任务可用时，就取出队首的任务在处理器中执行。

![image](https://github.com/user-attachments/assets/739c4359-ca96-448e-9294-2dc8f7844c3d)

> 这个 run_queue 必须支持多生产者多消费者模型（MPMC）。一般使用一个侵入式链表。侵入式意味着任务结构包括一个指向运行队列中下一个任务的指针，而不是用链接列表节点包装该任务。这样就避免了 push 和 pop 操作的内存分配。它可以使用无锁的 push 操作，但是 pop 操作需要一个互斥锁来协调消费者（技术上可以实现无锁消费者队列，但是实际上锁的开销小于为了避免锁的开销）。

> 在实现通用线程池时，通常使用此方法，因为它具有多个优点： 调度公平 实现是相对简单的。 现成的队列可以与上面概述的处理器循环配对。

> 调度公平性意味着任务按先进先出的顺序进行调度。先入队的任务将首先执行（FIFO）。 通用调度器试图做到公平，有一些办法可以辅助，例如使用fork-join对计算进行并行化，但是最重要的因素是最终的计算速度，而不是每个子任务的公平性。
这个调度有一个负面的点，就是所有的处理器争夺队首的任务。对一般的线程池而言，这不会有什么影响。因为处理器花费在执行任务上的时间远比从队首弹出任务要多得多。然而，Rust 的异步任务从队首弹出以后只花费一点点时间就执行完。在这个场景下，争夺队首任务的开销就变得很重要了。

## moon是`Many processors, each with their own run queue`

> 另一种设计调度器的方式是：使用多个单线程调度器。每个处理器从自身的和处理器核心绑定的 run_queue 中获取任务。这就完全避免了线程间同步的问题。由于Rust 的任务模型要求能够从任何线程往队列中推入任务，因此仍然需要一种线程安全的将任务推入调度器中的方法。每个处理器的 run_queue 支持线程安全的推入任务（多生产者单消费者模型）或者每个处理器有两个 run_queue：一个不同步队列和一个线程安全队列。

![image](https://github.com/user-attachments/assets/a5a471be-ad7c-455d-afcc-1b1dbc198f96)

> 这种策略被海星采用（海星是一个高性能 cpp 开源 NoSQL 数据库项目）。因为这种策略几乎没有同步发生，所以非常快。但是不是万能药。除非工作负载完全均匀，否则某些处理器将在其他处理器满载时变为空闲，从而导致资源利用不足。发生这种情况是因为任务被固定到特定的处理器。 批量调度单个处理器上的一堆任务时，会出现饿死其他处理器的问题。

**我认为游戏服务器基本都会出现难以拆分的热点服务，如大世界地图之类的, 这种模型是比较适合游戏服务器业务的, 并且相比`One queue, many processors` 模型有更高的响应能力**

## 参考

https://tokio.rs/blog/2019-10-scheduler

https://zhuanlan.zhihu.com/p/363374062

**Comment by sniper00** [comment]
> ag多的话内存会不会涨的比较厉害

关于Actor模型内存占用问题, 这个就需要自己衡量了, 空的LuaVM大概占用200KB内存, 对于绝大多数项目不是问题。

以下是Actor模型的好处 https://github.com/ejoy/ant/wiki/ActorModel#%E5%9F%BA%E4%BA%8E-actor-%E7%9A%84%E5%B9%B6%E5%8F%91%E6%A8%A1%E5%9E%8B:

> Lua 有非常轻量的虚拟机作为沙盒隔离同一个进程内的多个服务，非常适合实现 actor 模型。使用它给我们带来的好处不仅仅是并行带来的延迟下降，还天然让一个复杂的程序拆解成若干高内聚低耦合的服务。每个服务不仅运行流程互不干扰、状态独立，甚至内存都是完全隔离的。

> 对 Lua 这种动态语言，GC 造成的延迟是游戏这种实时业务必须面对的问题。很多其它的引擎一旦嵌入 python javascript mono 等虚拟机，都难以减轻虚拟机 gc 带来的偶尔停顿。但如果把程序分成到多个虚拟机中，每个虚拟机承载的对象数量都会相应下降，对应的 GC 开销也随之下降。
