### ISSUE TITLE
想做一个棋牌服务器可以用这个框架？

### ISSUE THREAD

**Issue by Apoll95** [sniper00/moon#182]
想做一个棋牌服务器可以用这个框架？

**Comment by sniper00** [comment]
框架不限制游戏类型

**Comment by Apoll95** [comment]
大佬 棋牌子游戏服务器是设计成独占线程服务还是共享线程服务好？

**Comment by sniper00** [comment]
> 大佬 棋牌子游戏服务器是设计成独占线程服务还是共享线程服务好？ 

房间服务用共享的，大厅用独占的，就是玩家数关联越密集的用独占的。

**Comment by Apoll95** [comment]
大佬 如果子游戏服务器用c++写 如何与该框架适配 还是建议子游戏服务器用lua写？
