### ISSUE TITLE
有debug_console服务吗？

### ISSUE THREAD

**Issue by libla** [sniper00/moon#183]
虽然使用不便，但可以作为一个最终调整的手段

**Comment by sniper00** [comment]
没有直接提供debug console服务，但提供了相关API。游戏console应该是是管理批量 进程的，可以参考demo的实现：

单独开启进程，提供 telnet/http 端口，批量转发请求到对应节点进程:
https://github.com/sniper00/MoonDemo/blob/master/server/main_hub.lua
https://github.com/sniper00/MoonDemo/blob/master/server/game/service_hub.lua

节点进程开启对用服务
https://github.com/sniper00/MoonDemo/blob/master/server/game/node/Console.lua#L34
